main: com.abbydiode.afkhunger.App
name: ${project.name}
version: ${project.version}
description: ${project.description}
author: https://github.com/abbydiode
website: ${project.url}
api-version: 1.17

commands:
   afkhunger:
      description: Check if afkhunger is properly installed