main: com.abbydiode.afkhunger.App
name: Abbys-AFKHunger
version: 1.1.1
description: Slowly deduct food from players that are idle to discourage idling
author: abbydiode
website: https://www.spigotmc.org/resources/abbys-afk-hunger.73024/
api-version: 1.17

commands:
   afkhunger:
      description: Check if afkhunger is properly installed