# Time in seconds before player is considered idle
afkTime: 600
# Time in seconds it should take to deduct half a bar
hungerTime: 600
# How often in ticks to check for idle players, higher values perform better but are less accurate (1200 ~= 1 minute)
interval: 1200