name: Abbys-AFKHunger
version: 1.1.1
author: abbydiode
main: com.abbydiode.afkhunger.App
description: Slowly deduct food from players that are idle to discourage idling
api-version: 1.17
website: https://www.spigotmc.org/resources/abbys-afk-hunger.73024/

commands:
   afkhunger:
      description: Check if afkhunger is properly installed